---
- hosts: tfdemo
  become: yes
  become_method: sudo

# Playbook to install dependencies for docker and install docker 
- import_playbook: install_docker.yml

# Playbook to start the nginx server
- import_playbook: start_nginx.yml

# Playbook to install golang
- import_playbook: install_golang.yml

# Playbook to start the golang-go
- import_playbook: start_golang.yml