---
- hosts: tfdemo
  become: yes
  become_method: sudo

  tasks:
    # Does apt update 
    - name: update cache
      apt:
        update_cache: yes
    # Install  teh dependency packge pip
    - name: Install the package pip
      apt:
        name: pip

    - name: Install docker using docker.io
      apt:
        pkg:
          - docker.io

# add ubuntu user to docker group
    - name: Add user to docker group
      user:
        name: "{{ansible_user}}"
        group: docker

    - name: Install Docker Module for Python
      pip:
        name: docker
      become: yes



